src/accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
#    path('', views.index),
   path('register/', views.register, name="register"),
   path('login/',auth_views.LoginView.as_view(template_name="login.html"), name="login"),
   path('logout/',auth_views.LogoutView.as_view(next_page='mangas:list-mangas'),name='logout'),
]

src/mangareader/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import TemplateView
import notifications.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('mangas/', include('mangas.urls', namespace='mangas')),
    # user related path
    path("accounts/", include("accounts.urls", namespace='accounts')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

src/mangas/urls.py
from django.urls import path
from django.contrib import admin
from mangas.views import (
  ListMangaView,
  CreateMangaView,
  UpdateMangaView,
  UploadVolumeView,
  UploadChapterView,
  DisplayContentView,
  ListVolumeView,
  MyMangasView,
)
from mangas import views

app_name = 'mangas'

urlpatterns = [
    path('list-mangas/', ListMangaView.as_view(), name='list-mangas'),
    path('create-manga/', CreateMangaView.as_view(), name='create-manga'),
    path('my-mangas/', MyMangasView.as_view(), name='my-mangas'),
    path('update-manga/<int:pk>', UpdateMangaView.as_view(), name='update-manga'),
    path('delete-manga/<int:pk>', views.delete_manga, name='delete-manga'),
    path('upload-volume/<int:pk>', UploadVolumeView.as_view(), name='upload-volume'),
    path('upload-chapter/<int:pk>', UploadChapterView.as_view(), name='upload-chapter'),
    path('display-volume/<int:pk>', ListVolumeView.as_view(), name='display-volume'),
    path('content/<int:pk>/<str:volume_id>/<str:chapter_name>', DisplayContentView.as_view(), name='content'),
    path('subscribe-manga/<int:pk>', views.subscribe_manga, name='subscribe-manga'),
    path('search_results/', views.search_mangas, name='search'),
    path('read-notiifcations/', views.read_notifications, name='read-notifications')
]

src/mangas/models.py
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.shortcuts import render


# Create your models here.
class Manga(models.Model):
    name = models.CharField(max_length=224, null=False, blank=False)
    content = models.TextField(max_length=1000, null=False, blank=False)
    type = models.TextField(max_length=224, null=False, blank=False)
    num_of_volumes = models.IntegerField(default=0, null=False, blank=False)
    author = models.TextField(max_length=254, null=False, blank=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    cover = models.ImageField(upload_to='cover')

    def __unicode__(self):
        return self.content
  
    def get_absolute_url(self):
        return reverse('mangas:list-mangas', kwargs={})


def path_file_name(instance, filename):
    result = 'content/' + instance.manga.name + '/' + instance.name + '/' + filename
    return result


def path_chapter_name(instance, filename):
    result = 'content/' + instance.manga.name + '/' + instance.volume.name + '/' + instance.name + '/' + filename
    return result


class Volume(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    # images = models.FileField(upload_to=path_file_name)
    manga = models.ForeignKey(Manga, on_delete=models.CASCADE, null=True, blank=True)
    num_of_chapters = models.IntegerField(default=0, null=False, blank=False)
    timestamp = models.DateField(auto_now_add=True)

    def __unicode__(self):
        return self.content 

class Subscription(models.Model):
    manga = models.ForeignKey(Manga, on_delete=models.CASCADE)
    username = models.CharField(max_length=100, null=False, blank=False)
    timestamp = models.DateField(auto_now_add=True)

    def __unicode__(self):
        return self.content    
    

class Chapter(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    images = models.FileField(upload_to=path_chapter_name)
    manga = models.ForeignKey(Manga, on_delete=models.CASCADE, null=True, blank=True)
    volume = models.ForeignKey(Volume, on_delete=models.CASCADE, null=True, blank=True)

    def __unicode__(self):
        return self.content    

    # def get_absolute_url(self):
    #     return reverse(template_name='mangas/content.html', kwargs={})

src/mangas/forms.py
from django import forms
from .models import Manga, Volume, Chapter

class CreateMangaForm(forms.ModelForm):
    class Meta:
        model = Manga
        fields = ['name', 'content', 'type', 'cover']

class CreateVolumeForm(forms.ModelForm):
    class Meta:
        model = Volume
        fields = ['name', 'manga']
        widgets = {
            'images': forms.FileInput(attrs={'multiple': True})
        }

class CreateChapterForm(forms.ModelForm):
    class Meta:
        model = Chapter
        fields = ['volume', 'name', 'images', 'manga']
        widgets = {
            'images': forms.FileInput(attrs={'multiple': True})
        }
        

src/mangas/views.py
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from .forms import CreateMangaForm, CreateVolumeForm, CreateChapterForm
from django.urls import reverse
from zipfile import ZipFile
from notifications.signals import notify

from django.contrib.auth.models import User
from .models import Manga, Chapter, Subscription, Volume

# Create your views here.
class ListMangaView(ListView):
    model = Manga
    def get(self, request, *args, **kwargs):
        template_name = 'mangas/list-mangas.html'
        notifications = ''
        if request.user.username == '':
            print("anonymous")
        else:
            user = User.objects.get(username=request.user.username)
            # print(user.notifications.unread())
            notifications = user.notifications.unread()
            print(len(notifications))

            for notification in user.notifications.unread():
                print(notification.verb)
            print(request.user.username)
            
        obj = {
            'mangas': Manga.objects.all(),
            'username': request.user.username,
            'notifications': notifications,
            'num_of_notifications': len(notifications),
            # 'user': User.objects.get(id=1)
            # 'notifications'
            # 'len': len(request.user.username),
        }
        # print("a",request.user.username, "aa")
        return render(request, template_name, obj)


class CreateMangaView(SuccessMessageMixin, CreateView):
    template_name = 'mangas/create-manga.html'
    form_class = CreateMangaForm
    success_message = 'Create Manga successfully!'

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            author = request.user.username
            cover = request.FILES.get('cover')
            data = request.POST
            Manga.objects.create(name=data['name'], content=data['content'], type=data['type'], author=author, cover=cover)
            return redirect('mangas:list-mangas')
        else:
            print("invalid")
            return self.form_invalid(form)
        

def search_mangas(request):
    if request.method == 'POST':
        keyword = request.POST['keyword']
        mangas = Manga.objects.filter(name__icontains=keyword)
        template_name = 'mangas/search_mangas.html'

        print(mangas)

        notifications = ''
        if request.user.username == '':
            print("anonymous")
        else:
            user = User.objects.get(username=request.user.username)
            # print(user.notifications.unread())
            notifications = user.notifications.unread()
            print(len(notifications))

            for notification in user.notifications.unread():
                print(notification.verb)
            print(request.user.username)
            
        obj = {
            'mangas': mangas,
            'username': request.user.username,
            'notifications': notifications,
            'num_of_notifications': len(notifications),
            'searched': keyword,
        }

        return render(request, template_name, obj)
    else:
        template_name = 'mangas/search_mangas.html'
        obj = {
        }
        return render(request, template_name, obj)


class UpdateMangaView(SuccessMessageMixin, UpdateView):
    template_name = 'mangas/edit-manga.html'
    model = Manga
    fields = ['name', 'content', 'type']
    success_message = 'Update Manga successfully!'

    def get_success_url(self): 
        return reverse('mangas:list-mangas', kwargs={})
    

class ListVolumeView(ListView):
    model = Volume
    def get(self, request, pk, *args, **kwargs):
        template_name = 'mangas/list-volumes.html'
        username = request.user.username
        manga = Manga.objects.get(id=pk)
        volumes = Volume.objects.values('name', 'manga_id', 'timestamp').distinct()
        # volumes = Volume.objects.filter(manga=manga)
        lst = []
        for i in range(len(volumes)):
            if volumes[i]['manga_id'] == pk:
                lst.append(volumes[i])

        volumes = lst
        print(volumes)

        for i in range(len(volumes)):
            # print(volume.id)
            volume = Volume.objects.get(name=volumes[i]['name'], manga=manga)
            chapter = Chapter.objects.filter(volume=volume)[0]
            # print(chapters)
            lst[i]['chapter'] = chapter.name

        
        # for i in range(len(volumes)):
        #     volume = Volume.objects.filter(name=volumes[i]['name'], manga=manga)
        #     chapter = Chapter.objects.filter(volume=volume)
        #     print(chapter)
        #     volumes[i]['chapter'] = chapter.name 
        
        print(len(volumes))

        is_subscribed = 2
        if Subscription.objects.filter(manga_id=pk, username=username).exists() == True:
            is_subscribed = 1
        else:
            is_subscribed = 0
        # print(is_subscribed)
        obj = {
            'volumes': volumes,
            'username': username,
            'manga': Manga.objects.get(id=pk),
            'is_subscribed': is_subscribed,
        }
        return render(request, template_name, obj)


# class DisplayContentView(ListView):
#     model = Volume
#     def get(self, request, pk, volume_id, *args, **kwargs):
#         template_name = 'mangas/content.html'
#         volumes = Volume.objects.filter(name=volume_id)
#         obj = {
#             'volumes': Chapter.objects.filter(volume=volumes[0]),
#             'manga': Manga.objects.get(id=pk)
#         }
#         return render(request, template_name, obj)
    

class DisplayContentView(ListView):
    model = Chapter
    def get(self, request, pk, volume_id, chapter_name, *args, **kwargs):
        template_name = 'mangas/content.html'
        manga = Manga.objects.get(id=pk)
        volume = Volume.objects.get(name=volume_id, manga=manga)
        chapters = Chapter.objects.filter(volume=volume, name=chapter_name, manga=manga)
        all_chapters = Chapter.objects.filter(manga=manga)
        chapter_names = all_chapters.values('name', 'volume_id', 'manga_id').distinct()
        lst = []
        cur_chapter = chapters.values('name', 'volume_id', 'manga_id').distinct()[0]

        for name in chapter_names:
            lst.append(name)

        prev_chapter = ''
        next_chapter = ''
        next_volume = ''
        prev_volume = ''
        next = 'chapter'
        prev = 'chapter'    
    
        # print(lst)
        cur = lst.index(cur_chapter)
        if cur < len(lst) - 1:
            next_chapter = lst[cur + 1]['name']
            next_volume = Volume.objects.get(id=lst[cur + 1]['volume_id'])
        if cur > 0:
            prev_chapter = lst[cur - 1]['name']
            prev_volume = Volume.objects.get(id=lst[cur - 1]['volume_id'])
        
        # print(next_volume, prev_volume)

        if next_volume != '' and next_volume.name != volume.name:
            next = 'volume'
        if prev_volume != '' and prev_volume.name != volume.name: 
            prev = 'volume'
        obj = {
            'volume': volume,
            'chapters': chapters,
            'chapterName': cur_chapter['name'],
            'manga': manga,
            'next_chapter': next_chapter,
            'prev_chapter': prev_chapter,
            'next_vol': next_volume,
            'prev_vol': prev_volume,
            'prev': prev,
            'next': next,
        }
        return render(request, template_name, obj)



class MyMangasView(ListView):
    def get(self, request, *args, **kwargs):
        template_name = 'mangas/my-mangas.html'


        mangas = Manga.objects.filter(author=request.user.username)
        obj = {
            'mangas': mangas,
        }
        return render(request, template_name, obj)
    

class UploadVolumeView(SuccessMessageMixin, CreateView):
    model = Volume
    template_name = 'mangas/upload-volume.html'
    form_class = CreateVolumeForm
    success_url = 'mangas:list-mangas'


    def post(self, request, pk, *args, **kwargs):
        manga = Manga.objects.get(id=pk)
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        sender = User.objects.get(username=request.user.username)
        receivers = Subscription.objects.filter(manga_id=pk)
        for receiver_user in receivers:
            receiver = User.objects.get(username=receiver_user.username)
            notify.send(sender=sender, recipient=receiver, verb=pk, description='New volume from ' + manga.name)

        images = request.FILES.getlist('images')
        for image in images:
            print(image.name)
        data = request.POST
        num_of_chapters = data['num_of_chapters']
        num_of_pages = 0
        volume_name = data['name']
        cur_page = 1
        cur_chap = 1
        new_volumes = 1
        if num_of_chapters != 'Each file is a chapter':
            num_of_chapters = int(num_of_chapters)
            num_of_pages = int(len(images) / num_of_chapters)
        else:
            num_of_chapters = len(images)

        if volume_name == '' and images[0].name[-4:] != '.zip':
            volume_name = 'Volume ' + str(manga.num_of_volumes + 1)
        
        if images[0].name[-4:] != '.zip':
            volume = Volume.objects.create(name=volume_name, manga=manga, num_of_chapters=num_of_chapters)
        
        if form.is_valid():
            print("valid")
            # print(images)
            for image in images:
                if image.name[-4:] != '.zip':
                    if data['num_of_chapters'] == 'Each file is a chapter':
                        print('default')
                        Chapter.objects.create(name = 'Chapter ' + str(cur_chap), images = image, manga=manga, volume=volume)

src/mangas/templates/layouts/layout.html
<!-- mangas/templates/layouts/layout.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock title %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700&display=swap" rel="stylesheet">

        <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500&display=swap" rel="stylesheet">

        <link href="https://fonts.googleapis.com/css?family=Source+Serif+Pro:400,600&display=swap" rel="stylesheet">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

        <link rel="stylesheet" href="{% static 'style_font.css' %}">

        <link rel="stylesheet" href="{% static 'owl.carousel.min.css' %}">

        <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">

        <link rel="stylesheet" href="{% static 'style_noti.css' %}">

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
        
        <style>
          footer {
            background-color: #555;
            color: white;
            height: 20px;
            bottom: 0%;
            position: fixed;
          }
          
          footer p {
            font-size: small;
          }

          .active {
            background-color: #CDE990;
          }
          #search-button {
            height: 30px;
          }
          #form1 {
            height: 29px;
            width: 300px;
          }
          .text-right {
            text-align: right;
          }

          .center-div {
            display: block;
            margin-left: auto;
            margin-right: auto;
            object-position: center;
          }

          #next-chap {
            position: relative;
            left: 600px;
            height: 30px;
            width: 120px;
            align-items: flex-end;
            /* right: 0%; */
            /* object-position: right; */
          } 

          #prev-chap {
            height: 30px;
            width: 120px;
          }
          
          #side {
            background-color: #E4E4E4;
          }

          #main {
            background-color: white;
          }

          .nav-link:hover {
            color: var(--bs-primary);
          }
          p {
            color: black;
          }
          
        </style>


        <script type="text/javascript">

          document.addEventListener("DOMContentLoaded", function(){

            document.querySelectorAll('.sidebar .nav-link').forEach(function(element){

              element.addEventListener('click', function (e) {

                let nextEl = element.nextElementSibling;
                let parentEl  = element.parentElement;	

                if(nextEl) {
                  e.preventDefault();	
                  let mycollapse = new bootstrap.Collapse(nextEl);

                    if(nextEl.classList.contains('show')){
                      mycollapse.hide();
                    } else {
                      mycollapse.show();
                      // find other submenus with class=show
                      var opened_submenu = parentEl.parentElement.querySelector('.submenu.show');
                      // if it exists, then close all of them
                    if(opened_submenu){
                      new bootstrap.Collapse(opened_submenu);
                    }

                    }
                  }

              });
            })

          }); 
          // DOMContentLoaded  end
        </script>
    </head>
    <body>
        
        <div class="">
            <div class="row content">
              <div class="col-sm-3 sidebar">
                <ul id="nav_accordion" class="nav flex-column"><br>
                  {% if user.username %}
                    <li class="nav-item">
                      <h4>Xin chào {{user.username}} {% block notifications %}{% endblock notifications %}</h4>
                    </li>
                    <br>
                    <li class = "nav-item">
                      <a class="nav-link" href="{% url 'mangas:list-mangas' %}">Home</a></li>
                    </li>
                    <li class = "nav-item has-submenu">
                      <a class="nav-link" href=""> Account <i class="bi small bi-caret-down-fill"></i> </a>
                        <ul class="submenu collapse">
                          <li><a class="nav-link" href="{% url 'accounts:logout' %}">Logout </a></li>
                        </ul>
                    </li>
                    <!-- <li class="nav-item">
                      <a class="nav-link" href="{% url 'accounts:logout' %}">Đăng xuất</a>
                    </li> -->
                  {% else %}
                    <li class = "nav-item">
                      <a class="nav-link" href="{% url 'mangas:list-mangas' %}">Home</a></li>
                    </li>
                    <li class = "nav-item has-submenu">
                      <a class="nav-link" href=""> Account <i class="bi small bi-caret-down-fill"></i> </a>
                        <ul class="submenu collapse">
                          <li><a class="nav-link" href="{% url 'accounts:register' %}">Register</a></li>
                          <li><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
                        </ul>
                    </li>
                    <!-- <li class="nav-item">
                      <a class="nav-link" href="{% url 'accounts:register' %}">Đăng ký</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'accounts:login' %}">Đăng nhập</a>
                    </li> -->
                  {% endif %}

                  <li class = "nav-item has-submenu">
                    <a class="nav-link" href=""> Mangas <i class="bi small bi-caret-down-fill"></i> </a>
                      <ul class="submenu collapse">
                        <li><a class="nav-link" href="{% url 'mangas:list-mangas' %}">List Mangas</a></li>
                        <li><a class="nav-link" href="{% url 'mangas:create-manga' %}">Create Mangas</a></li>
                        <li><a class="nav-link" href="{% url 'mangas:my-mangas' %}">My Mangas</a></li>
                      </ul>
                  </li>
                </ul>

                <!-- <ul class="nav flex-column">
                  {% if messages %}
                    {% for message in messages %}
                      <div class="alert alert-success">
                        <strong>{{ message }}</strong>
                      </div>
                    {% endfor %}
                  {% endif %}
                  {% if success %}
                    <div class="alert alert-success">
                        <strong>{{success}}</strong>
                    </div>
                  {% endif %}
                  <li {% if request.path == "/mangas/list-mangas/" %}class="nav-item active"{% endif %}>
                    <a href="{% url 'mangas:list-mangas' %}">List Mangas</a>
                  </li>
                  <li {% if request.path == "/mangas/create-manga/" %}class="nav-item active"{% endif %}>
                    <a href="{% url 'mangas:create-manga' %}">Create Mangas</a>
                  </li>
                </ul><br> -->
              </div>        
              <div  class="col-sm-9">
                  {% block content %}
                  {% endblock content %}
              </div>
            </div>
            <div class="push"></div>
          </div>          
          <div class="footer">
            <footer class="container-fluid">
              <p>Mangareader</p>
            </footer>
          </div>
    </body>
</html>