src/mangareader/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import TemplateView
import notifications.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('mangas/', include('mangas.urls', namespace='mangas')),
    # user related path
    path("accounts/", include("accounts.urls", namespace='accounts')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

src/mangas/urls.py
from django.urls import path
from django.contrib import admin
from mangas.views import (
  ListMangaView,
  CreateMangaView,
  UpdateMangaView,
  UploadVolumeView,
  UploadChapterView,
  DisplayContentView,
  ListVolumeView,
  MyMangasView,
)
from mangas import views

app_name = 'mangas'

urlpatterns = [
    path('list-mangas/', ListMangaView.as_view(), name='list-mangas'),
    path('create-manga/', CreateMangaView.as_view(), name='create-manga'),
    path('my-mangas/', MyMangasView.as_view(), name='my-mangas'),
    path('update-manga/<int:pk>', UpdateMangaView.as_view(), name='update-manga'),
    path('delete-manga/<int:pk>', views.delete_manga, name='delete-manga'),
    path('upload-volume/<int:pk>', UploadVolumeView.as_view(), name='upload-volume'),
    path('upload-chapter/<int:pk>', UploadChapterView.as_view(), name='upload-chapter'),
    path('display-volume/<int:pk>', ListVolumeView.as_view(), name='display-volume'),
    path('content/<int:pk>/<str:volume_id>/<str:chapter_name>', DisplayContentView.as_view(), name='content'),
    path('subscribe-manga/<int:pk>', views.subscribe_manga, name='subscribe-manga'),
    path('search_results/', views.search_mangas, name='search'),
    path('read-notiifcations/', views.read_notifications, name='read-notifications')
]

src/mangas/models.py
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.shortcuts import render


# Create your models here.
class Manga(models.Model):
    name = models.CharField(max_length=224, null=False, blank=False)
    content = models.TextField(max_length=1000, null=False, blank=False)
    type = models.TextField(max_length=224, null=False, blank=False)
    num_of_volumes = models.IntegerField(default=0, null=False, blank=False)
    author = models.TextField(max_length=254, null=False, blank=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    cover = models.ImageField(upload_to='cover')

    def __unicode__(self):
        return self.content
  
    def get_absolute_url(self):
        return reverse('mangas:list-mangas', kwargs={})


def path_file_name(instance, filename):
    result = 'content/' + instance.manga.name + '/' + instance.name + '/' + filename
    return result


def path_chapter_name(instance, filename):
    result = 'content/' + instance.manga.name + '/' + instance.volume.name + '/' + instance.name + '/' + filename
    return result


class Volume(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    # images = models.FileField(upload_to=path_file_name)
    manga = models.ForeignKey(Manga, on_delete=models.CASCADE, null=True, blank=True)
    num_of_chapters = models.IntegerField(default=0, null=False, blank=False)
    timestamp = models.DateField(auto_now_add=True)

    def __unicode__(self):
        return self.content 

class Subscription(models.Model):
    manga = models.ForeignKey(Manga, on_delete=models.CASCADE)
    username = models.CharField(max_length=100, null=False, blank=False)
    timestamp = models.DateField(auto_now_add=True)

    def __unicode__(self):
        return self.content    
    

class Chapter(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    images = models.FileField(upload_to=path_chapter_name)
    manga = models.ForeignKey(Manga, on_delete=models.CASCADE, null=True, blank=True)
    volume = models.ForeignKey(Volume, on_delete=models.CASCADE, null=True, blank=True)

    def __unicode__(self):
        return self.content    

    # def get_absolute_url(self):
    #     return reverse(template_name='mangas/content.html', kwargs={})

src/mangas/forms.py
from django import forms
from .models import Manga, Volume, Chapter

class CreateMangaForm(forms.ModelForm):
    class Meta:
        model = Manga
        fields = ['name', 'content', 'type', 'cover']

class CreateVolumeForm(forms.ModelForm):
    class Meta:
        model = Volume
        fields = ['name', 'manga']
        widgets = {
            'images': forms.FileInput(attrs={'multiple': True})
        }

class CreateChapterForm(forms.ModelForm):
    class Meta:
        model = Chapter
        fields = ['volume', 'name', 'images', 'manga']
        widgets = {
            'images': forms.FileInput(attrs={'multiple': True})
        }
        

src/mangas/views.py
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from .forms import CreateMangaForm, CreateVolumeForm, CreateChapterForm
from django.urls import reverse
from zipfile import ZipFile
from notifications.signals import notify

from django.contrib.auth.models import User
from .models import Manga, Chapter, Subscription, Volume

# Create your views here.
class ListMangaView(ListView):
    model = Manga
    def get(self, request, *args, **kwargs):
        template_name = 'mangas/list-mangas.html'
        notifications = ''
        if request.user.username == '':
            print("anonymous")
        else:
            user = User.objects.get(username=request.user.username)
            # print(user.notifications.unread())
            notifications = user.notifications.unread()
            print(len(notifications))

            for notification in user.notifications.unread():
                print(notification.verb)
            print(request.user.username)
            
        obj = {
            'mangas': Manga.objects.all(),
            'username': request.user.username,
            'notifications': notifications,
            'num_of_notifications': len(notifications),
            # 'user': User.objects.get(id=1)
            # 'notifications'
            # 'len': len(request.user.username),
        }
        # print("a",request.user.username, "aa")
        return render(request, template_name, obj)


class CreateMangaView(SuccessMessageMixin, CreateView):
    template_name = 'mangas/create-manga.html'
    form_class = CreateMangaForm
    success_message = 'Create Manga successfully!'

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            author = request.user.username
            cover = request.FILES.get('cover')
            data = request.POST
            Manga.objects.create(name=data['name'], content=data['content'], type=data['type'], author=author, cover=cover)
            return redirect('mangas:list-mangas')
        else:
            print("invalid")
            return self.form_invalid(form)
        

def search_mangas(request):
    if request.method == 'POST':
        keyword = request.POST['keyword']
        mangas = Manga.objects.filter(name__icontains=keyword)
        template_name = 'mangas/search_mangas.html'

        print(mangas)

        notifications = ''
        if request.user.username == '':
            print("anonymous")
        else:
            user = User.objects.get(username=request.user.username)
            # print(user.notifications.unread())
            notifications = user.notifications.unread()
            print(len(notifications))

            for notification in user.notifications.unread():
                print(notification.verb)
            print(request.user.username)
            
        obj = {
            'mangas': mangas,
            'username': request.user.username,
            'notifications': notifications,
            'num_of_notifications': len(notifications),
            'searched': keyword,
        }

        return render(request, template_name, obj)
    else:
        template_name = 'mangas/search_mangas.html'
        obj = {
        }
        return render(request, template_name, obj)


class UpdateMangaView(SuccessMessageMixin, UpdateView):
    template_name = 'mangas/edit-manga.html'
    model = Manga
    fields = ['name', 'content', 'type']
    success_message = 'Update Manga successfully!'

    def get_success_url(self): 
        return reverse('mangas:list-mangas', kwargs={})
    

class ListVolumeView(ListView):
    model = Volume
    def get(self, request, pk, *args, **kwargs):
        template_name = 'mangas/list-volumes.html'
        username = request.user.username
        manga = Manga.objects.get(id=pk)
        volumes = Volume.objects.values('name', 'manga_id', 'timestamp').distinct()
        # volumes = Volume.objects.filter(manga=manga)
        lst = []
        for i in range(len(volumes)):
            if volumes[i]['manga_id'] == pk:
                lst.append(volumes[i])

        volumes = lst
        print(volumes)

        for i in range(len(volumes)):
            # print(volume.id)
            volume = Volume.objects.get(name=volumes[i]['name'], manga=manga)
            chapter = Chapter.objects.filter(volume=volume)[0]
            # print(chapters)
            lst[i]['chapter'] = chapter.name

        
        # for i in range(len(volumes)):
        #     volume = Volume.objects.filter(name=volumes[i]['name'], manga=manga)
        #     chapter = Chapter.objects.filter(volume=volume)
        #     print(chapter)
        #     volumes[i]['chapter'] = chapter.name 
        
        print(len(volumes))

        is_subscribed = 2
        if Subscription.objects.filter(manga_id=pk, username=username).exists() == True:
            is_subscribed = 1
        else:
            is_subscribed = 0
        # print(is_subscribed)
        obj = {
            'volumes': volumes,
            'username': username,
            'manga': Manga.objects.get(id=pk),
            'is_subscribed': is_subscribed,
        }
        return render(request, template_name, obj)


# class DisplayContentView(ListView):
#     model = Volume
#     def get(self, request, pk, volume_id, *args, **kwargs):
#         template_name = 'mangas/content.html'
#         volumes = Volume.objects.filter(name=volume_id)
#         obj = {
#             'volumes': Chapter.objects.filter(volume=volumes[0]),
#             'manga': Manga.objects.get(id=pk)
#         }
#         return render(request, template_name, obj)
    

class DisplayContentView(ListView):
    model = Chapter
    def get(self, request, pk, volume_id, chapter_name, *args, **kwargs):
        template_name = 'mangas/content.html'
        manga = Manga.objects.get(id=pk)
        volume = Volume.objects.get(name=volume_id, manga=manga)
        chapters = Chapter.objects.filter(volume=volume, name=chapter_name, manga=manga)
        all_chapters = Chapter.objects.filter(manga=manga)
        chapter_names = all_chapters.values('name', 'volume_id', 'manga_id').distinct()
        lst = []
        cur_chapter = chapters.values('name', 'volume_id', 'manga_id').distinct()[0]

        for name in chapter_names:
            lst.append(name)

        prev_chapter = ''
        next_chapter = ''
        next_volume = ''
        prev_volume = ''
        next = 'chapter'
        prev = 'chapter'    
    
        # print(lst)
        cur = lst.index(cur_chapter)
        if cur < len(lst) - 1:
            next_chapter = lst[cur + 1]['name']
            next_volume = Volume.objects.get(id=lst[cur + 1]['volume_id'])
        if cur > 0:
            prev_chapter = lst[cur - 1]['name']
            prev_volume = Volume.objects.get(id=lst[cur - 1]['volume_id'])
        
        # print(next_volume, prev_volume)

        if next_volume != '' and next_volume.name != volume.name:
            next = 'volume'
        if prev_volume != '' and prev_volume.name != volume.name: 
            prev = 'volume'
        obj = {
            'volume': volume,
            'chapters': chapters,
            'chapterName': cur_chapter['name'],
            'manga': manga,
            'next_chapter': next_chapter,
            'prev_chapter': prev_chapter,
            'next_vol': next_volume,
            'prev_vol': prev_volume,
            'prev': prev,
            'next': next,
        }
        return render(request, template_name, obj)



class MyMangasView(ListView):
    def get(self, request, *args, **kwargs):
        template_name = 'mangas/my-mangas.html'


        mangas = Manga.objects.filter(author=request.user.username)
        obj = {
            'mangas': mangas,
        }
        return render(request, template_name, obj)
    

class UploadVolumeView(SuccessMessageMixin, CreateView):
    model = Volume
    template_name = 'mangas/upload-volume.html'
    form_class = CreateVolumeForm
    success_url = 'mangas:list-mangas'


    def post(self, request, pk, *args, **kwargs):
        manga = Manga.objects.get(id=pk)
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        sender = User.objects.get(username=request.user.username)
        receivers = Subscription.objects.filter(manga_id=pk)
        for receiver_user in receivers:
            receiver = User.objects.get(username=receiver_user.username)
            notify.send(sender=sender, recipient=receiver, verb=pk, description='New volume from ' + manga.name)

        images = request.FILES.getlist('images')
        for image in images:
            print(image.name)
        data = request.POST
        num_of_chapters = data['num_of_chapters']
        num_of_pages = 0
        volume_name = data['name']
        cur_page = 1
        cur_chap = 1
        new_volumes = 1
        if num_of_chapters != 'Each file is a chapter':
            num_of_chapters = int(num_of_chapters)
            num_of_pages = int(len(images) / num_of_chapters)
        else:
            num_of_chapters = len(images)

        if volume_name == '' and images[0].name[-4:] != '.zip':
            volume_name = 'Volume ' + str(manga.num_of_volumes + 1)
        
        if images[0].name[-4:] != '.zip':
            volume = Volume.objects.create(name=volume_name, manga=manga, num_of_chapters=num_of_chapters)
        
        if form.is_valid():
            print("valid")
            # print(images)
            for image in images:
                if image.name[-4:] != '.zip':
                    if data['num_of_chapters'] == 'Each file is a chapter':
                        print('default')
                        Chapter.objects.create(name = 'Chapter ' + str(cur_chap), images = image, manga=manga, volume=volume)

src/mangas/templates/mangas/list-mangas.html
<!-- mangas/templates/mangas/list-mangas.html -->
{% extends "layouts/layout.html" %}
{% block title %}
    List Mangas {{ block.super }}
{% endblock title %}

{% block notifications %}
  <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarSupportedContent"> -->
      <ul class="nav justify-content-center">
        <li class="nav-item">
          <div class="dropdown custom-dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-link" aria-haspopup="true" aria-expanded="false">
              <!-- <span class="wrap-icon badge-notification"></span> -->
              <i class="fa-solid fa-bell fa-lg"></i>
              <span class="number">{{num_of_notifications}}</span>
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
              <div class="title-wrap d-flex align-items-center">
                <h3 class="title mb-3">Notifications</h3>
                <!-- <a href="{% url 'notifications:mark_all_as_read' %}" class="small ml-auto">Mark all as read</a> -->
                <a href="{% url 'mangas:read-notifications' %}" class="ml-auto">Mark all as read</a>
              </div>
              <ul class="custom-notifications">
                {% for notification in notifications %}
                  <li class="unread">
                    
                    <a href="{% url 'mangas:display-volume' notification.verb %}">{{ notification.description }}</a>
                    <!-- <p>{{ notification.verb }}</p> -->
                  </li>
                {% endfor %}
              </ul>
              <!-- <p class="text-center m-0 p-0"><a href="{% url 'notifications:unread' %}" class="small">View All</a></p> -->
            </div>
          </div>
        </li>
      </ul>
    <!-- </div>
  </nav> -->
{% endblock notifications %}

{% block content %} 
  <form action="{% url 'mangas:search' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <input name="keyword" type="search" id="form1" placeholder="Search..." />
      <button id="search-button" class="btn btn-primary btn-lg" type="submit">
        <i class="fas fa-search"></i> 
      </button>
      <br> 
      <!-- <label id="search-label" class="form-label" for="form1">Search</label> -->
    </div>
  </form>

  <h4><small>List Mangas</small></h4>
  <hr>
  {% if mangas %}
    {% for manga in mangas %}
    <a href="{% url 'mangas:display-volume' manga.id %}"><h2>{{manga.name}}</h2></a>
    <h5><span class="glyphicon glyphicon-time"></span> Post at {{manga.timestamp}}</h5>
    <p><b>Content:</b> {{manga.content}}</p>
    <p><b>Type:</b> {{manga.type}}</p>
    <img src = "{{manga.cover.url}}" height=300px>
    <p><b>{{manga.author}}</b></p>
    <p> <b> {{manga.num_of_volumes}} Volumes </b></p>
    {% if username == manga.author %}
      <div>
        <div class="dropdown-menu-link">
          <button class="btn btn-primary btn-lg dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Edit Manga
          </button>
          <div class="dropdown-menu">
            <a class="dropdown-item" role="button" href="{% url 'mangas:update-manga' manga.id %}">Edit</a>
            <a class="dropdown-item" role="button" href="{% url 'mangas:upload-volume' manga.id %}">Upload Volumes</a>
            <a class="dropdown-item" href="{% url 'mangas:upload-chapter' manga.id %}">Upload chapters</a>
          </div>
          <!-- <a class="btn btn-primary btn-lg" role="button" href="{% url 'mangas:update-manga' manga.id %}">Edit</a> -->
          <a class="btn btn-primary btn-lg" role="button" href="{% url 'mangas:delete-manga' manga.id %}" onclick="return confirm('Are you sure you want to delete this manga?');">Delete</a>
        </div>  
      </div>
      <!-- <a class="btn btn-primary btn-lg" role="button" href="{% url 'mangas:upload-volume' manga.id %}">Upload Volumes</a> -->
    {% endif %}
    
    <br><br>
    {% endfor %}
  {% else %}
    No manga.
  {% endif %}
{% endblock content %}

src/mangas/templates/mangas/list-volumes.html
<!-- mangas/templates/mangas/list-chapters.html -->

{% extends "layouts/layout.html" %}
{% block title %}
    List Volumes {{ block.super }}
{% endblock title %}
{% block content %}
  <h4><small>List Volumes</small></h4>
  <h4>{{manga.name}}</h4>
  <hr>
  {% if username != "" %}
    {% if username != manga.author %}
      {% if is_subscribed == 0 %}
        <a class="btn btn-primary btn-lg" role="button" href="{% url 'mangas:subscribe-manga' manga.id %}">Subscribe Manga</a>
      {% else %}
        <a href="#" class="btn btn-primary btn-lg disabled" role="button" aria-disabled="true">
          Subscribed
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check" viewBox="0 0 16 16">
            <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
          </svg>
        </a>  
      {% endif %}
    {% endif %} 
  {% endif %}
  <br><br>

  <table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Volume</th>
        <th scope="col">Timestamp</th>
      </tr>
    </thead>
    <tbody>
      {% if volumes %}
        {% for volume in volumes %}
          {% if volume.manga_id == manga.id %}
            <tr>
              <td><a href="{% url 'mangas:content' pk=manga.id volume_id=volume.name chapter_name=volume.chapter %}"> {{volume.name}} </a></td>
              <th scope="row">{{volume.timestamp}}</th>
            </tr>
          {% endif %}
        {% endfor %}
      {% endif %}
    </tbody>
  </table>

  <!-- {% if volumes %}
    {% for volume in volumes %}
        {% if volume.manga_id == manga.id %}
          <p><a href="#"> {{volume.name}} </a></p>
        {% endif %}
    <br><br>
    {% endfor %}
  {% else %}
    No manga.
  {% endif %} -->
{% endblock content %}

src/mangas/templates/mangas/my-mangas.html
<!-- mangas/templates/mangas/list-mangas.html -->
{% extends "layouts/layout.html" %}
{% block title %}
    My Mangas {{ block.super }}
{% endblock title %}

{% block notifications %}
  <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarSupportedContent"> -->
      <ul class="nav justify-content-center">
        <li class="nav-item">
          <div class="dropdown custom-dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-link" aria-haspopup="true" aria-expanded="false">
              <!-- <span class="wrap-icon badge-notification"></span> -->
              <i class="fa-solid fa-bell fa-lg"></i>
              <span class="number">{{num_of_notifications}}</span>
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
              <div class="title-wrap d-flex align-items-center">
                <h3 class="title mb-3">Notifications</h3>
                <!-- <a href="{% url 'notifications:mark_all_as_read' %}" class="small ml-auto">Mark all as read</a> -->
                <a href="{% url 'mangas:read-notifications' %}" class="ml-auto">Mark all as read</a>
              </div>
              <ul class="custom-notifications">
                {% for notification in notifications %}
                  <li class="unread">
                    
                    <a href="{% url 'mangas:display-volume' notification.verb %}">{{ notification.description }}</a>
                    <!-- <p>{{ notification.verb }}</p> -->
                  </li>
                {% endfor %}
              </ul>
              <!-- <p class="text-center m-0 p-0"><a href="{% url 'notifications:unread_list' %}" class="small">View All</a></p> -->
            </div>
          </div>
        </li>
      </ul>
    <!-- </div>
  </nav> -->
{% endblock notifications %}

{% block content %} 
  <form action="{% url 'mangas:search' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <input name="keyword" type="search" id="form1" placeholder="Search..." />
      <button id="search-button" class="btn btn-primary btn-lg" type="submit">
        <i class="fas fa-search"></i> 
      </button>
      <br> 
      <!-- <label id="search-label" class="form-label" for="form1">Search</label> -->
    </div>
  </form>

  <h4><small>List Mangas</small></h4>
  <hr>
  {% if mangas %}
    {% for manga in mangas %}
    <a href="{% url 'mangas:display-volume' manga.id %}"><h2>{{manga.name}}</h2></a>
    <h5><span class="glyphicon glyphicon-time"></span> Post at {{manga.timestamp}}</h5>
    <p><b>Content:</b> {{manga.content}}</p>
    <p><b>Type:</b> {{manga.type}}</p>
    <img src = "{{manga.cover.url}}" height=300px>
    <p><b>{{manga.author}}</b></p>
    <p> <b> {{manga.num_of_volumes}} Volumes </b></p>
    {% if username == manga.author %}
      <div>
        <div class="dropdown-menu-link">
          <button class="btn btn-primary btn-lg dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Edit Manga
          </button>
          <div class="dropdown-menu">
            <a class="dropdown-item" role="button" href="{% url 'mangas:update-manga' manga.id %}">Edit</a>
            <a class="dropdown-item" role="button" href="{% url 'mangas:upload-volume' manga.id %}">Upload Volumes</a>
            <a class="dropdown-item" href="{% url 'mangas:upload-chapter' manga.id %}">Upload chapters</a>
          </div>
          <!-- <a class="btn btn-primary btn-lg" role="button" href="{% url 'mangas:update-manga' manga.id %}">Edit</a> -->
          <a class="btn btn-primary btn-lg" role="button" href="{% url 'mangas:delete-manga' manga.id %}" onclick="return confirm('Are you sure you want to delete this manga?');">Delete</a>
        </div>  
      </div>
      <!-- <a class="btn btn-primary btn-lg" role="button" href="{% url 'mangas:upload-volume' manga.id %}">Upload Volumes</a> -->
    {% endif %}
    
    <br><br>
    {% endfor %}
  {% else %}
    No manga.
  {% endif %}
{% endblock content %}

src/mangas/templates/mangas/search_mangas.html
<!-- mangas/templates/mangas/list-mangas.html -->
{% extends "layouts/layout.html" %}
{% block title %}
    List Mangas {{ block.super }}
{% endblock title %}

{% block notifications %}
  <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarSupportedContent"> -->
      <ul class="nav justify-content-center">
        <li class="nav-item">
          <div class="dropdown custom-dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-link" aria-haspopup="true" aria-expanded="false">
              <!-- <span class="wrap-icon badge-notification"></span> -->
              <i class="fa-solid fa-bell fa-lg"></i>
              <span class="number">{{num_of_notifications}}</span>
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
              <div class="title-wrap d-flex align-items-center">
                <h3 class="title mb-3">Notifications</h3>
                <!-- <a href="{% url 'notifications:mark_all_as_read' %}" class="small ml-auto">Mark all as read</a> -->
                <a href="{% url 'mangas:read-notifications' %}" class="ml-auto">Mark all as read</a>
              </div>
              <ul class="custom-notifications">
                {% for notification in notifications %}
                  <li class="unread">
                    
                    <a href="{% url 'mangas:display-volume' notification.verb %}">{{ notification.description }}</a>
                    <!-- <p>{{ notification.verb }}</p> -->
                  </li>
                {% endfor %}
              </ul>
              <p class="text-center m-0 p-0"><a href="{% url 'notifications:unread' %}" class="small">View All</a></p>
            </div>
          </div>
        </li>
      </ul>
    <!-- </div>
  </nav> -->
{% endblock notifications %}

{% block content %} 
  
<form action="{% url 'mangas:search' %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <input name="keyword" type="search" id="form1" placeholder="Search..." />
    <button id="search-button" class="btn btn-primary btn-lg" type="submit">
      <i class="fas fa-search"></i> 
    </button>
    <br>
    {% if searched %}
      <label id="search-label" class="form-label" for="form1">Search for <span><b>{{searched}}</b></span></label>
    {% else %}
      <label id="search-label" class="form-label" for="form1">You haven't searched</label>
    {% endif %}
  </div>
</form>

  <h4><small>List Mangas</small></h4>
  <hr>
  {% if mangas %}
    {% for manga in mangas %}
    <a href="{% url 'mangas:display-volume' manga.id %}"><h2>{{manga.name}}</h2></a>
    <h5><span class="glyphicon glyphicon-time"></span> Post at {{manga.timestamp}}</h5>
    <p><b>Content:</b> {{manga.content}}</p>
    <p><b>Type:</b> {{manga.type}}</p>
    <img src = "{{manga.cover.url}}" height=300px>
    <p>{{manga.author}}</p>
    <p> <b> {{manga.num_of_volumes}} Volumes </b></p>
    {% if username == manga.author %}
      <a class="btn btn-primary btn-lg" role="button" href="{% url 'mangas:update-manga' manga.id %}">Edit</a>
      <a class="btn btn-primary btn-lg" role="button" href="{% url 'mangas:delete-manga' manga.id %}" onclick="return confirm('Are you sure you want to delete this manga?');">Delete</a>
      <a class="btn btn-primary btn-lg" role="button" href="{% url 'mangas:upload-volume' manga.id %}">Upload Volumes</a>
    {% endif %}
    
    <br><br>
    {% endfor %}
  {% else %}
    No manga.
  {% endif %}
{% endblock content %}